# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rivendell < Formula
  desc "Rivendell CLI for AI coding agents and developer integrations"
  homepage "https://rivendell.health"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rivendell-health/homebrew-cli/releases/download/v0.2.1/rivendell_0.2.1_darwin_amd64.tar.gz"
      sha256 "85cf39a13cea7eb9edc5ab20ac5dbc7aa239998c9743a16721cd363a2b597d75"

      define_method(:install) do
        bin.install "rivendell"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rivendell-health/homebrew-cli/releases/download/v0.2.1/rivendell_0.2.1_darwin_arm64.tar.gz"
      sha256 "5e84271837105bf9faa51598ffd062065364e710008bcef9ebd4bae595954108"

      define_method(:install) do
        bin.install "rivendell"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rivendell-health/homebrew-cli/releases/download/v0.2.1/rivendell_0.2.1_linux_amd64.tar.gz"
      sha256 "39b2a4bd495df0826a7472f136c46859852c3fa682749e96f915b499edafa23c"
      define_method(:install) do
        bin.install "rivendell"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rivendell-health/homebrew-cli/releases/download/v0.2.1/rivendell_0.2.1_linux_arm64.tar.gz"
      sha256 "87727a42f66b77ab9c8293234a031aad32e0364ce01c57094c401d9822c66d4f"
      define_method(:install) do
        bin.install "rivendell"
      end
    end
  end

  test do
    system "#{bin}/rivendell version"
  end
end
