# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rivendell < Formula
  desc "Rivendell CLI for AI coding agents and developer integrations"
  homepage "https://rivendell.health"
  version "0.1.8"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rivendell-health/homebrew-cli/releases/download/v0.1.8/rivendell_0.1.8_darwin_amd64.tar.gz"
      sha256 "1f659bf4f41dba3dbf31c78ae7d18cceac5bb74436624c831b1870c86406842a"

      define_method(:install) do
        bin.install "rivendell"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rivendell-health/homebrew-cli/releases/download/v0.1.8/rivendell_0.1.8_darwin_arm64.tar.gz"
      sha256 "abc0d38c2f50c13cf8b43a4c1a13c22daebb20e94839c9931eb38a58df3d04e9"

      define_method(:install) do
        bin.install "rivendell"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rivendell-health/homebrew-cli/releases/download/v0.1.8/rivendell_0.1.8_linux_amd64.tar.gz"
      sha256 "1a9c66d1289c31f1935f83415c011748d59cb9ed1b1ae6fa2e700035577dae88"
      define_method(:install) do
        bin.install "rivendell"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rivendell-health/homebrew-cli/releases/download/v0.1.8/rivendell_0.1.8_linux_arm64.tar.gz"
      sha256 "2f981163647e3a900271d03d3128dfcb42ad73914873823c5c3618bd300b68f0"
      define_method(:install) do
        bin.install "rivendell"
      end
    end
  end

  test do
    system "#{bin}/rivendell version"
  end
end
