# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rivendell < Formula
  desc "Rivendell CLI for AI coding agents and developer integrations"
  homepage "https://rivendell.health"
  version "0.1.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rivendell-health/web/releases/download/v0.1.7/rivendell_0.1.7_darwin_amd64.tar.gz"
      sha256 "39c3957bfd90e4f022013a3db97f8e24c884ade7651396a718eeef2fa1a82a44"

      define_method(:install) do
        bin.install "rivendell"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rivendell-health/web/releases/download/v0.1.7/rivendell_0.1.7_darwin_arm64.tar.gz"
      sha256 "5ffbe6911b4b83fdeb4b00f2c6be80120da644070f4a18a6ed659dbe0cf61035"

      define_method(:install) do
        bin.install "rivendell"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rivendell-health/web/releases/download/v0.1.7/rivendell_0.1.7_linux_amd64.tar.gz"
      sha256 "b7ef3aab890bdc2eb8f7fd471bbe6c7e94ffd2e7011234eda90f2c5bcde5a26e"
      define_method(:install) do
        bin.install "rivendell"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rivendell-health/web/releases/download/v0.1.7/rivendell_0.1.7_linux_arm64.tar.gz"
      sha256 "0a6c28e5d3c32dd9feda0773e8d320211ea3490589a59c51f71746d8a3fcebd4"
      define_method(:install) do
        bin.install "rivendell"
      end
    end
  end

  test do
    system "#{bin}/rivendell version"
  end
end
